/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZhCnRouteImport } from './routes/zh-cn'
import { Route as ZhRouteImport } from './routes/zh'
import { Route as PtRouteImport } from './routes/pt'
import { Route as NlRouteImport } from './routes/nl'
import { Route as KoRouteImport } from './routes/ko'
import { Route as JaRouteImport } from './routes/ja'
import { Route as ItRouteImport } from './routes/it'
import { Route as FrRouteImport } from './routes/fr'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EsRouteImport } from './routes/es'
import { Route as DeRouteImport } from './routes/de'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideRoundRobinRouteImport } from './routes/guide.round-robin'
import { Route as GuideKnockoutRouteImport } from './routes/guide.knockout'
import { Route as GuideAmericanoRouteImport } from './routes/guide.americano'

const ZhCnRoute = ZhCnRouteImport.update({
  id: '/zh-cn',
  path: '/zh-cn',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhRoute = ZhRouteImport.update({
  id: '/zh',
  path: '/zh',
  getParentRoute: () => rootRouteImport,
} as any)
const PtRoute = PtRouteImport.update({
  id: '/pt',
  path: '/pt',
  getParentRoute: () => rootRouteImport,
} as any)
const NlRoute = NlRouteImport.update({
  id: '/nl',
  path: '/nl',
  getParentRoute: () => rootRouteImport,
} as any)
const KoRoute = KoRouteImport.update({
  id: '/ko',
  path: '/ko',
  getParentRoute: () => rootRouteImport,
} as any)
const JaRoute = JaRouteImport.update({
  id: '/ja',
  path: '/ja',
  getParentRoute: () => rootRouteImport,
} as any)
const ItRoute = ItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const DeRoute = DeRouteImport.update({
  id: '/de',
  path: '/de',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoundRobinRoute = GuideRoundRobinRouteImport.update({
  id: '/guide/round-robin',
  path: '/guide/round-robin',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideKnockoutRoute = GuideKnockoutRouteImport.update({
  id: '/guide/knockout',
  path: '/guide/knockout',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideAmericanoRoute = GuideAmericanoRouteImport.update({
  id: '/guide/americano',
  path: '/guide/americano',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/de': typeof DeRoute
  '/es': typeof EsRoute
  '/faq': typeof FaqRoute
  '/fr': typeof FrRoute
  '/it': typeof ItRoute
  '/ja': typeof JaRoute
  '/ko': typeof KoRoute
  '/nl': typeof NlRoute
  '/pt': typeof PtRoute
  '/zh': typeof ZhRoute
  '/zh-cn': typeof ZhCnRoute
  '/guide/americano': typeof GuideAmericanoRoute
  '/guide/knockout': typeof GuideKnockoutRoute
  '/guide/round-robin': typeof GuideRoundRobinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/de': typeof DeRoute
  '/es': typeof EsRoute
  '/faq': typeof FaqRoute
  '/fr': typeof FrRoute
  '/it': typeof ItRoute
  '/ja': typeof JaRoute
  '/ko': typeof KoRoute
  '/nl': typeof NlRoute
  '/pt': typeof PtRoute
  '/zh': typeof ZhRoute
  '/zh-cn': typeof ZhCnRoute
  '/guide/americano': typeof GuideAmericanoRoute
  '/guide/knockout': typeof GuideKnockoutRoute
  '/guide/round-robin': typeof GuideRoundRobinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/de': typeof DeRoute
  '/es': typeof EsRoute
  '/faq': typeof FaqRoute
  '/fr': typeof FrRoute
  '/it': typeof ItRoute
  '/ja': typeof JaRoute
  '/ko': typeof KoRoute
  '/nl': typeof NlRoute
  '/pt': typeof PtRoute
  '/zh': typeof ZhRoute
  '/zh-cn': typeof ZhCnRoute
  '/guide/americano': typeof GuideAmericanoRoute
  '/guide/knockout': typeof GuideKnockoutRoute
  '/guide/round-robin': typeof GuideRoundRobinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/de'
    | '/es'
    | '/faq'
    | '/fr'
    | '/it'
    | '/ja'
    | '/ko'
    | '/nl'
    | '/pt'
    | '/zh'
    | '/zh-cn'
    | '/guide/americano'
    | '/guide/knockout'
    | '/guide/round-robin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/de'
    | '/es'
    | '/faq'
    | '/fr'
    | '/it'
    | '/ja'
    | '/ko'
    | '/nl'
    | '/pt'
    | '/zh'
    | '/zh-cn'
    | '/guide/americano'
    | '/guide/knockout'
    | '/guide/round-robin'
  id:
    | '__root__'
    | '/'
    | '/de'
    | '/es'
    | '/faq'
    | '/fr'
    | '/it'
    | '/ja'
    | '/ko'
    | '/nl'
    | '/pt'
    | '/zh'
    | '/zh-cn'
    | '/guide/americano'
    | '/guide/knockout'
    | '/guide/round-robin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeRoute: typeof DeRoute
  EsRoute: typeof EsRoute
  FaqRoute: typeof FaqRoute
  FrRoute: typeof FrRoute
  ItRoute: typeof ItRoute
  JaRoute: typeof JaRoute
  KoRoute: typeof KoRoute
  NlRoute: typeof NlRoute
  PtRoute: typeof PtRoute
  ZhRoute: typeof ZhRoute
  ZhCnRoute: typeof ZhCnRoute
  GuideAmericanoRoute: typeof GuideAmericanoRoute
  GuideKnockoutRoute: typeof GuideKnockoutRoute
  GuideRoundRobinRoute: typeof GuideRoundRobinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zh-cn': {
      id: '/zh-cn'
      path: '/zh-cn'
      fullPath: '/zh-cn'
      preLoaderRoute: typeof ZhCnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh': {
      id: '/zh'
      path: '/zh'
      fullPath: '/zh'
      preLoaderRoute: typeof ZhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt': {
      id: '/pt'
      path: '/pt'
      fullPath: '/pt'
      preLoaderRoute: typeof PtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nl': {
      id: '/nl'
      path: '/nl'
      fullPath: '/nl'
      preLoaderRoute: typeof NlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko': {
      id: '/ko'
      path: '/ko'
      fullPath: '/ko'
      preLoaderRoute: typeof KoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja': {
      id: '/ja'
      path: '/ja'
      fullPath: '/ja'
      preLoaderRoute: typeof JaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it': {
      id: '/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof ItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de': {
      id: '/de'
      path: '/de'
      fullPath: '/de'
      preLoaderRoute: typeof DeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/round-robin': {
      id: '/guide/round-robin'
      path: '/guide/round-robin'
      fullPath: '/guide/round-robin'
      preLoaderRoute: typeof GuideRoundRobinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/knockout': {
      id: '/guide/knockout'
      path: '/guide/knockout'
      fullPath: '/guide/knockout'
      preLoaderRoute: typeof GuideKnockoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/americano': {
      id: '/guide/americano'
      path: '/guide/americano'
      fullPath: '/guide/americano'
      preLoaderRoute: typeof GuideAmericanoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeRoute: DeRoute,
  EsRoute: EsRoute,
  FaqRoute: FaqRoute,
  FrRoute: FrRoute,
  ItRoute: ItRoute,
  JaRoute: JaRoute,
  KoRoute: KoRoute,
  NlRoute: NlRoute,
  PtRoute: PtRoute,
  ZhRoute: ZhRoute,
  ZhCnRoute: ZhCnRoute,
  GuideAmericanoRoute: GuideAmericanoRoute,
  GuideKnockoutRoute: GuideKnockoutRoute,
  GuideRoundRobinRoute: GuideRoundRobinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
