/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PtRouteImport } from './routes/pt'
import { Route as NlRouteImport } from './routes/nl'
import { Route as KoRouteImport } from './routes/ko'
import { Route as JaRouteImport } from './routes/ja'
import { Route as ItRouteImport } from './routes/it'
import { Route as FrRouteImport } from './routes/fr'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EsRouteImport } from './routes/es'
import { Route as EnRouteImport } from './routes/en'
import { Route as DeRouteImport } from './routes/de'
import { Route as IndexRouteImport } from './routes/index'

const PtRoute = PtRouteImport.update({
  id: '/pt',
  path: '/pt',
  getParentRoute: () => rootRouteImport,
} as any)
const NlRoute = NlRouteImport.update({
  id: '/nl',
  path: '/nl',
  getParentRoute: () => rootRouteImport,
} as any)
const KoRoute = KoRouteImport.update({
  id: '/ko',
  path: '/ko',
  getParentRoute: () => rootRouteImport,
} as any)
const JaRoute = JaRouteImport.update({
  id: '/ja',
  path: '/ja',
  getParentRoute: () => rootRouteImport,
} as any)
const ItRoute = ItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const DeRoute = DeRouteImport.update({
  id: '/de',
  path: '/de',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/de': typeof DeRoute
  '/en': typeof EnRoute
  '/es': typeof EsRoute
  '/faq': typeof FaqRoute
  '/fr': typeof FrRoute
  '/it': typeof ItRoute
  '/ja': typeof JaRoute
  '/ko': typeof KoRoute
  '/nl': typeof NlRoute
  '/pt': typeof PtRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/de': typeof DeRoute
  '/en': typeof EnRoute
  '/es': typeof EsRoute
  '/faq': typeof FaqRoute
  '/fr': typeof FrRoute
  '/it': typeof ItRoute
  '/ja': typeof JaRoute
  '/ko': typeof KoRoute
  '/nl': typeof NlRoute
  '/pt': typeof PtRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/de': typeof DeRoute
  '/en': typeof EnRoute
  '/es': typeof EsRoute
  '/faq': typeof FaqRoute
  '/fr': typeof FrRoute
  '/it': typeof ItRoute
  '/ja': typeof JaRoute
  '/ko': typeof KoRoute
  '/nl': typeof NlRoute
  '/pt': typeof PtRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/de'
    | '/en'
    | '/es'
    | '/faq'
    | '/fr'
    | '/it'
    | '/ja'
    | '/ko'
    | '/nl'
    | '/pt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/de'
    | '/en'
    | '/es'
    | '/faq'
    | '/fr'
    | '/it'
    | '/ja'
    | '/ko'
    | '/nl'
    | '/pt'
  id:
    | '__root__'
    | '/'
    | '/de'
    | '/en'
    | '/es'
    | '/faq'
    | '/fr'
    | '/it'
    | '/ja'
    | '/ko'
    | '/nl'
    | '/pt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeRoute: typeof DeRoute
  EnRoute: typeof EnRoute
  EsRoute: typeof EsRoute
  FaqRoute: typeof FaqRoute
  FrRoute: typeof FrRoute
  ItRoute: typeof ItRoute
  JaRoute: typeof JaRoute
  KoRoute: typeof KoRoute
  NlRoute: typeof NlRoute
  PtRoute: typeof PtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pt': {
      id: '/pt'
      path: '/pt'
      fullPath: '/pt'
      preLoaderRoute: typeof PtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nl': {
      id: '/nl'
      path: '/nl'
      fullPath: '/nl'
      preLoaderRoute: typeof NlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko': {
      id: '/ko'
      path: '/ko'
      fullPath: '/ko'
      preLoaderRoute: typeof KoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja': {
      id: '/ja'
      path: '/ja'
      fullPath: '/ja'
      preLoaderRoute: typeof JaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it': {
      id: '/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof ItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de': {
      id: '/de'
      path: '/de'
      fullPath: '/de'
      preLoaderRoute: typeof DeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeRoute: DeRoute,
  EnRoute: EnRoute,
  EsRoute: EsRoute,
  FaqRoute: FaqRoute,
  FrRoute: FrRoute,
  ItRoute: ItRoute,
  JaRoute: JaRoute,
  KoRoute: KoRoute,
  NlRoute: NlRoute,
  PtRoute: PtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
